id: P010334
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159396
  title: གངས་སེང་འཚོལ་བ།
  author: ''
  volumes:
    6211e964f2ad435b9e8152de6661b4a8:
      image_group_id: I2PD18822
      title: ''
      volume_number: 1
      total_pages: 306
