id: IFDAED71C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:12:16+00:00'
last_modified: '2022-06-08T12:49:39.168337+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159396
  title: གངས་སེང་འཚོལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4B95:
      image_group_id: I2PD18822
      title: ''
      total_pages: 306
      order: 1
      base_file: 4B95.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
